version: "3"
services:
  recipe_app:
    image: recipe-app-api
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"